CREATE SCHEMA IF NOT EXISTS cliente_beneficio_bd;

CREATE TABLE IF NOT EXISTS cliente_beneficio_bd.beneficio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    descuento INTEGER NOT NULL
 );