spring.application.name=MSBoleta
server.port=8084

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO

spring.output.ansi.enabled=ALWAYS

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3

spring.sql.init.mode=never
spring.sql.init.data-locations=

spring.jpa.defer-datasource-initialization=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=boleta_service_bd

spring.flyway.enabled=true
spring.flyway.default-schema=boleta_service_bd
spring.flyway.schemas=boleta_service_bd
spring.flyway.locations=classpath:db/migration

clientebeneficio.api.base-url=${CLIENTEBENEFICIO_API_BASE_URL:http://127.0.0.1:8083}
inventario.api.base-url=${INVENTARIO_API_BASE_URL:http://127.0.0.1:8081}
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
