services:

  eureka:
    build: ./eureka
    image: eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"

  apigateway:
    build: ./apigateway
    image: apigateway:latest
    container_name: apigateway
    ports:
      - "8088:8088"
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka

  MSBoleta:
    build: ./MSBoleta
    image: msboleta:latest
    container_name: MSBoleta
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8084:8084"
    depends_on:
      - eureka
    environment:
      - DB_URL=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
      - DB_USERNAME=postgres.uqxsjrztlkdtqeurpdun
      - DB_PASSWORD=ClienteBeneficio
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka
      - CLIENTEBENEFICIO_API_BASE_URL=http://MSclienteBeneficio:8083
      - INVENTARIO_API_BASE_URL=http://ms-catalogo:8081

  MSclienteBeneficio:
    build: ./MSclienteBeneficio
    image: msclientebeneficio:latest
    container_name: MSclienteBeneficio
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8083:8083"
    depends_on:
      - eureka
    environment:
      - DB_URL=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
      - DB_USERNAME=postgres.uqxsjrztlkdtqeurpdun
      - DB_PASSWORD=ClienteBeneficio
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka

  ms-catalogo:
    build: ./ms-catalogo
    image: mscatagolo:latest
    container_name: ms-catalogo
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8081:8081"
    depends_on:
      - eureka
    environment:
      - DB_URL=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
      - DB_USERNAME=postgres.mhnpkltjyfnzcrrdyquq
      - DB_PASSWORD=Fullstack011V
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka

  ms-inventario:
    build: ./ms-inventario
    image: msinventario:latest
    container_name: ms-inventario
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8082:8082"
    depends_on:
      - eureka
    environment:
      - DB_URL=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres
      - DB_USERNAME=postgres.xjjbfnddjhiyfjcdocbp
      - DB_PASSWORD=Fullstack011V
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka

  ms-compraProveedor:
    build: ./ms-compraProveedor
    image: mscompraproveedor:latest
    container_name: ms-compraProveedor
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8086:8086"
    depends_on:
      - eureka
    environment:
      - BD_URL=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
      - BD_USER=postgres.wdymywqplyxxfxvngweg
      - BD_PASSWORD=Cristebyjona
      - EUREKA_URI=http://eureka:8761/eureka/
      - MICROSERVICIO_LOTE_URL=http://ms-inventario:8082
      - PROVEEDOR_API_BASE_URL=http://ms-proveedor:8085/api/proveedores

  ms-proveedor:
    build: ./ms-Proveedor
    image: msproveedor:latest
    container_name: ms-proveedor
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8085:8085"
    depends_on:
      - eureka
    environment:
      - DB_URL=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
      - DB_USERNAME=postgres.wdymywqplyxxfxvngweg
      - DB_PASSWORD=Cristebyjona
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka
      - MICROSERVICIO_FARMA_URL=http://ms-compraProveedor:8086

  ms-Proveedor:
    build: ./ms-proveedor
    image: msproveedor:latest
    container_name: ms-Proveedor
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8085:8085"
    depends_on:
      - eureka
    environment:
      - DB_URL=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
      - DB_USERNAME=postgres.ilwruhyhcqrzobdoisrc
      - DB_PASSWORD=Cristebyjona
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka


networks:
  default:
    name: microservicios-network