spring.application.name=proy
server.port=8085

logging.level.org.springframework.web=INFO
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO

spring.output.ansi.enabled=ALWAYS

# URL de conexión (la obtienes de Supabase)
spring.datasource.url=jdbc:postgresql://localhost:5432/farmacia

# Credenciales
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never

# Configuración de Hibernate/JPA
spring.jpa.defer-datasource-initialization=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.flyway.enabled=true
#spring.flyway.default-schema=bd_proveedor
#spring.flyway.schemas=bd_proveedor
#spring.flyway.locations=classpath:db/migration
