spring.application.name=proy
server.port=8081

# URL de conexión (la obtienes de Supabase)
spring.datasource.url=jdbc:postgresql://db.[tu-id-proyecto].supabase.co:5432/postgres

# Credenciales
spring.datasource.username=postgres
spring.datasource.password=[proveedor-123-XD]

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# de seguridad: Nunca subas tu contraseña real a GitHub. Usa variables de entorno o un archivo
