server:
  port: 8088

spring:
  application: 
    name: gateway
  cloud:
    gateway:
      routes:
        - id: MSBoleta
          uri: lb://MSBOLETA
          predicates:
            - Path=/api/boletas/**, /api/recetas-clientes/**
        - id: MSclienteBeneficio
          uri: lb://MSCLIENTEBENEFICIO
          predicates:
            - Path=/api/beneficios/**, /api/clientes/**
        - id: ms-catalogo
          uri: lb://MS-CATALOGO
          predicates:
            - Path=/api/v1/productos/**
        - id: ms-inventario
          uri: lb://MS-INVENTARIO
          predicates:
            - Path=/api/v1/inventario/**, /api/v1/lotes/**, /api/v1/movimientos/**, /api/v1/stock/**
        - id: ms-compraProveedor
          uri: lb://MS-COMPRAPROVEEDOR
          predicates:
            - Path=/api/compras/**
        - id: ms-proveedor
          uri: lb://MS-PROVEEDOR
          predicates:
            - Path=/api/proveedores/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG