CREATE SCHEMA IF NOT EXISTS boleta_service_bd;

CREATE TABLE IF NOT EXISTS boleta_service_bd.boleta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio BIGINT NOT NULL UNIQUE,
    cliente_run VARCHAR(8) NOT NULL,
    cliente_dv VARCHAR(1) NOT NULL,
    cliente_nombre VARCHAR(80) NOT NULL,
    cliente_apellido VARCHAR(80) NOT NULL,
    cliente_correo VARCHAR(80) NOT NULL,
    cliente_id_beneficio BIGINT,
    cliente_nombre_beneficio VARCHAR(80),
    cliente_descuento_entero INTEGER NOT NULL DEFAULT 0,
    porcentaje_descuento DECIMAL(5,4) NOT NULL DEFAULT 0,
    monto_descuento DECIMAL(12,2) NOT NULL DEFAULT 0,
    monto_neto DECIMAL(12,2) NOT NULL,
    iva DECIMAL(12,2) NOT NULL,
    monto_bruto DECIMAL(12,2) NOT NULL,
    fecha_emision TIMESTAMP NOT NULL,
    anulada BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_anulacion TIMESTAMP
);

CREATE TABLE IF NOT EXISTS boleta_service_bd.boleta_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    boleta_id BIGINT NOT NULL REFERENCES boleta_service_bd.boleta(id) ON DELETE CASCADE,
    sku_producto BIGINT NOT NULL,
    nombre_producto VARCHAR(255) NOT NULL,
    tipo_receta VARCHAR(50) NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario DECIMAL(12,2) NOT NULL,
    monto_linea DECIMAL(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS boleta_service_bd.receta_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_cliente VARCHAR(8) NOT NULL,
    tipo_receta VARCHAR(50) NOT NULL,
    folio_receta VARCHAR(50) NOT NULL,
    fecha_emision DATE NOT NULL,
    fecha_vencimiento DATE,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_receta_cliente UNIQUE (run_cliente, folio_receta)
);
