spring.application.name=ms-catalogo
server.port = 8081

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO

spring.output.ansi.enabled=ALWAYS

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.defer-datasource-initialization=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=esquema_catalogo

spring.flyway.enabled=true
spring.flyway.default-schema=esquema_catalogo
spring.flyway.schemas=esquema_catalogo
spring.flyway.locations=classpath:db/migrations