spring.application.name=farma
server.port=8086

spring.datasource.url=jdbc:postgresql://db.TU-REF.supabase.co:5432/farma
spring.datasource.username=postgres
spring.datasource.password=compra-26-XD

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
